### PR TITLE
Add BTN support

### PR DESCRIPTION
**Pull request by deed02392**

### CODE REVIEW

**Comment by erickok** [comment]
Thanks for the contribution. Entering an API key in a field marked username is a bit unclear. Maybe it should hide the username field so you are forced to use the password field. In any case, I am not sure if showing the password to users is the correct thing to do; ever. For your use case it makes sense, but generally not.

The actual BTN implementation looks good (although I cannot test it as I have no account there).

**Comment by deed02392** [comment]
Thanks Eric, I looked at making it possible to only require the password field to be completed but it won't show up as a search provider if that's empty. Hiding username and setting it to some default value would fix that. I appreciate the preference not to show password to a user, but as this is an api key I figured the frustration of entering it wrong was worse than if it's seen by someone (in which case it's still unlikely to be memorised and abused).

**Comment by erickok** [comment]
Merged manually. I added a proper token field for sites (only BTN at the moment) that use a token instead of username/password.

I haven't tested the actual BTN implementation as I do not have an account.

**Comment by deed02392** [comment]
Great, I will try to test the new token field etc. soon.

**Pull request merged**
