### PR TITLE
AsiaTorrents has become AvistaZ

### PR DESCRIPTION
**Pull request by ryliejamesthomas**
Changed all instances of asiatorrents to avistaz. Unsure if search and login URLs have changed though.

### CODE REVIEW

**Comment by ryliejamesthomas** [comment]
?

**Comment by erickok** [comment]
@ryliejamesthomas Sorry I can't do anything I have no access to the site so no way to test if it is working.

**Comment by ryliejamesthomas** [comment]
Ah, I understand. I can get you an invite if that helps.

**Comment by erickok** [comment]
Yup. erickok@gmail.com

**Comment by ryliejamesthomas** [comment]
Done. Invite needs to be activated within 24 hours.

**Comment by ryliejamesthomas** [comment]
Hmm, looks like URLs have changed.

- `https://avistaz.to/auth/login`
- `https://avistaz.to/torrents?in=0&search=[query]`
  - `in=0` searches all fields (filename, description, all files)

And you can create RSS feeds from searches now, too.

**Comment by erickok** [comment]
I'm afraid I am blocked though.
Their login uses a captha so teh Search Module can't really log in the way your browser does. And the RSS feeds are fixed to some search term (you have to create a feed first before using it) so there can be no free search. Not sure what I can do about it...

**Comment by ryliejamesthomas** [comment]
No worries. Thanks for looking into it.

**Pull request closed without merging**
