### PR TITLE
Add Sky Torrents (https://www.skytorrents.in) 

### PR DESCRIPTION
**Pull request by Niluge-KiWi**
* Forked from ExtraTorrentAdapter
* Sort by seeders (doesn't support sorting option yet)

### CODE REVIEW

**Comment by Niluge-KiWi** [comment]
This resolves #52.

**Comment by Niluge-KiWi** [comment]
Do not merge yet, there is an issue with spaces escaping: we have to generate `%20`, and we currently generate `+`, which drastically degrades the results quality.

**Comment by Niluge-KiWi** [comment]
Space escaping fixed as in `NyaaTorrentsAdapter`: after `URLEncoder.encode` the only `+` in the output are escaped spaces: we can simply replace them by `%20`.

**Comment by lozbrown** [comment]
@erickok Can we intergrate this, seems usefull

**Comment by erickok** [comment]
Thanks for the contribution! It would be great if you can maintain this, as I have no SkyTorrents account; or send me an invite so I can test and maintain.

**Comment by Niluge-KiWi** [comment]
This is a public website, no need for an account.

**Pull request merged**
